site_name: Landing

docs_dir: docs_src
draft_docs: vault
site_dir: docs

theme:
  name: landing

  favicon: "branding/favicon.png"
  avatar: "branding/logo.png"
  tagline: |
    /[lændɪŋ](http://ipa-reader.xyz/?text=lændɪŋ)/
  footer: |
      Compiled from markdown using [MkDocs](https://www.mkdocs.org/), hosted via [GitHub Pages](https://pages.github.com/).
  page_source: 
    link: https://github.com/TEParsons/mkdocs-landing
    icon: github
  socials:
    - label: Email
      link: mailto:todd.e.parsons@gmail.com
      icon: at
    - label: GitHub
      link: https://github.com/TEParsons/mkdocs-landing
      icon: github
    - label: Theme Gallery
      link: https://github.com/mkdocs/catalog?tab=readme-ov-file#-theming
      icon: book

hooks:
  - mkdocs_landing/hooks/md_filter.py
  - mkdocs_landing/hooks/layout.py
