site_name: Todd Parsons

docs_dir: docs_src
draft_docs: vault
site_dir: docs

theme:
  name: landing

  favicon: assets/tp.png
  avatar: assets/staff-picture.jpg
  background: "\"\""
  tagline: |
    he/him /[tɒd pɑsənz](http://ipa-reader.xyz/?text=tɒd%20pɑsənz)/
  footer: |
      Compiled from markdown using [MkDocs](https://www.mkdocs.org/), hosted via [GitHub Pages](https://pages.github.com/).
  page_source: 
    link: https://github.com/TEParsons/toddparsons
    icon: github
  socials:
    - label: Email
      link: mailto:todd.e.parsons@gmail.com
      icon: at
    - label: GitHub
      link: https://github.com/TEParsons
      icon: github
    - label: ORCiD
      link: https://orcid.org/0000-0002-6192-8414
      icon: orcid
    - label: Google Scholar
      link: https://scholar.google.co.uk/citations?user=dPnWdLUAAAAJ&hl=en
      icon: google-scholar
    - label: LinkedIn
      link: https://www.linkedin.com/in/todd-parsons-056a459a
      icon: linkedin


hooks:
  - mkdocs_landing/hooks/md_filter.py
  - mkdocs_landing/hooks/layout.py
